# version: '3.8'

services:
  frontend:
    container_name: handwash-frontend
    image: node:14
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm start"
    depends_on:
      - backend

  backend:
    container_name: handwash-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: handwash_backend:latest
    ports:
      - "4550:4550"
    volumes:
      - ./backend:/app/backend
      - ./runs:/app/runs
    command: uvicorn backend.main:app --host 0.0.0.0 --port 4550 --reload

volumes:
  backend:
  frontend: